#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs a minimal KDE desktop environment. (Approx. 600MB)'
HOSTBIN='startkde'
CHROOTBIN='crouton-noroot startkde'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install --minimal arch=,plasma-desktop \
    arch=kde-meta-kdeadmin, \
    arch=kde-meta-kdebase,kde-baseapps \
    arch=kde-meta-kdegraphics, \
    arch=kde-meta-kdepim, \
    arch=kde-meta-kdeplasma-addons, \
    arch=kde-meta-kdeutils, \
    arch=,kde-runtime \
    arch=pulseaudio,pulseaudio \
    arch=kdesdk-kate, \
    -- network-manager

if release -lt xenial -lt kali -lt stretch; then
    install --minimal kde-workspace
fi

TIPS="$TIPS
You can start KDE via the startkde host command: sudo startkde
"
